version: 2

project_name: terraform-provider-spacetraders

before:
  hooks:
    - go mod tidy

builds:
  - id: terraform-provider-spacetraders
    main: ./
    binary: terraform-provider-spacetraders_v{{ .Version }}
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .CommitDate }}
    goos:
      - freebsd
      - windows
      - linux
      - darwin
      - openbsd
      - solaris
    goarch:
      - amd64
      - arm
      - arm64
      - "386"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: openbsd
        goarch: arm
      - goos: openbsd
        goarch: arm64
      - goos: solaris
        goarch: "386"
      - goos: solaris
        goarch: arm
      - goos: solaris
        goarch: arm64
      - goos: windows
        goarch: arm64

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - src: terraform-registry-manifest.json
        dst: terraform-registry-manifest.json

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      - --batch
      - --pinentry-mode
      - loopback
      - --passphrase
      - "{{ .Env.GPG_PASSPHRASE }}"
      - --local-user
      - "{{ .Env.GPG_FINGERPRINT }}"
      - --output
      - "${signature}"
      - --detach-sign
      - "${artifact}"
    env:
      - GPG_TTY=/dev/null

release:
  draft: false

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
